# Generated by Django 4.2.7 on 2023-12-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plus',
        ),
    ]
