# Generated by Django 4.2.7 on 2024-01-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabProduction',
            fields=[
                ('id_production', models.AutoField(db_column='ID_Production', primary_key=True, serialize=False)),
                ('code_type_production', models.CharField(db_column='Code_Type_Production', max_length=2)),
                ('code_site', models.CharField(db_column='Code_site', max_length=500)),
                ('code_filiale', models.CharField(blank=True, db_column='Code_Filiale', max_length=5, null=True)),
                ('nt', models.CharField(blank=True, db_column='NT', max_length=4, null=True)),
                ('code_groupeactivite', models.CharField(blank=True, db_column='Code_GroupeActivite', max_length=4, null=True)),
                ('code_activite', models.CharField(blank=True, db_column='Code_Activite', max_length=4, null=True)),
                ('code_tache', models.CharField(blank=True, db_column='Code_Tache', max_length=4, null=True)),
                ('recepteur', models.CharField(blank=True, db_column='Recepteur', max_length=20, null=True)),
                ('code_produit', models.CharField(blank=True, db_column='Code_Produit', max_length=4, null=True)),
                ('code_unite_mesure', models.CharField(blank=True, db_column='Code_Unite_Mesure', max_length=4, null=True)),
                ('type_prestation', models.SmallIntegerField(blank=True, db_column='Type_Prestation', null=True)),
                ('mmaa', models.DateField(db_column='Mmaa')),
                ('quantite_1', models.FloatField(blank=True, db_column='Quantite_1', null=True)),
                ('valeur_1', models.DecimalField(blank=True, db_column='Valeur_1', decimal_places=4, max_digits=19, null=True)),
                ('quantite_2', models.FloatField(blank=True, db_column='Quantite_2', null=True)),
                ('valeur_2', models.DecimalField(blank=True, db_column='Valeur_2', decimal_places=4, max_digits=19, null=True)),
                ('quantite_3', models.FloatField(blank=True, db_column='Quantite_3', null=True)),
                ('valeur_3', models.DecimalField(blank=True, db_column='Valeur_3', decimal_places=4, max_digits=19, null=True)),
                ('prevu_realiser', models.CharField(db_column='Prevu_Realiser', max_length=1)),
                ('est_cloturer', models.BooleanField(blank=True, db_column='Est_Cloturer', null=True)),
                ('user_id', models.CharField(blank=True, db_column='User_ID', max_length=15, null=True)),
                ('date_modification', models.DateTimeField(blank=True, db_column='Date_Modification', null=True)),
            ],
            options={
                'db_table': 'dbo.Tab_Production',
            },
        ),
    ]
