# Generated by Django 4.2.7 on 2024-01-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tabproduction',
            table='Tab_Production',
        ),
    ]
