# Generated by Django 4.2.7 on 2024-01-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabproduction',
            options={},
        ),
    ]
