# Generated by Django 3.2.22 on 2023-11-08 12:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('code_client', models.CharField(db_column='Code_Client', max_length=500, primary_key=True, serialize=False)),
                ('type_client', models.PositiveSmallIntegerField(blank=True, db_column='Type_Client', null=True)),
                ('est_client_cosider', models.BooleanField(blank=True, db_column='Est_Client_Cosider')),
                ('libelle_client', models.CharField(blank=True, db_column='Libelle_Client', max_length=300, null=True)),
                ('nif', models.CharField(blank=True, db_column='NIF', max_length=50, null=True, unique=True)),
                ('raison_social', models.CharField(blank=True, db_column='Raison_Social', max_length=50, null=True)),
                ('num_registre_commerce', models.CharField(blank=True, db_column='Num_Registre_Commerce', max_length=20, null=True)),
                ('est_bloquer', models.BooleanField(db_column='Est_Bloquer', default=False)),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='Date_Modification')),
                ('user_id', models.ForeignKey(db_column='User_ID', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clients',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('src', models.ImageField(blank=True, default='default.png', upload_to='Images/Login')),
                ('est_bloquer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Images',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('code_site', models.CharField(db_column='Code_site', max_length=10, primary_key=True, serialize=False)),
                ('code_filiale', models.CharField(db_column='Code_Filiale', max_length=5)),
                ('code_region', models.CharField(blank=True, db_column='Code_Region', max_length=1, null=True)),
                ('libelle_site', models.CharField(blank=True, db_column='Libelle_Site', max_length=150, null=True)),
                ('code_agence', models.CharField(blank=True, db_column='Code_Agence', max_length=15, null=True)),
                ('type_site', models.PositiveSmallIntegerField(blank=True, db_column='Type_Site', null=True)),
                ('code_division', models.CharField(blank=True, db_column='Code_Division', max_length=15, null=True)),
                ('code_commune_site', models.CharField(blank=True, db_column='Code_Commune_Site', max_length=10, null=True)),
                ('jour_cloture_mouv_rh_paie', models.CharField(blank=True, db_column='Jour_Cloture_Mouv_RH_Paie', max_length=2, null=True)),
                ('date_ouverture_site', models.DateField(blank=True, db_column='Date_Ouverture_Site', null=True)),
                ('date_cloture_site', models.DateField(blank=True, db_column='Date_Cloture_Site', null=True)),
                ('est_bloquer', models.BooleanField(db_column='Est_Bloquer', default=False)),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='Date_Modification')),
                ('user_id', models.ForeignKey(db_column='User_ID', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sites',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='NT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nt', models.CharField(db_column='NT', max_length=20)),
                ('libelle_nt', models.TextField(blank=True, db_column='Libelle_NT', null=True)),
                ('date_ouverture_nt', models.DateField(blank=True, db_column='Date_Ouverture_NT', null=True)),
                ('date_cloture_nt', models.DateField(blank=True, db_column='Date_Cloture_NT', null=True)),
                ('est_bloquer', models.BooleanField(db_column='Est_Bloquer', default=False)),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='Date_Modification')),
                ('code_client', models.ForeignKey(db_column='Code_Client', on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.clients')),
                ('code_site', models.ForeignKey(db_column='Code_site', on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.sites')),
                ('user_id', models.ForeignKey(db_column='User_ID', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NT',
                'verbose_name_plural': 'NT',
                'unique_together': {('code_site', 'nt')},
            },
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avenant', models.PositiveBigIntegerField(db_column='avenant', default=0)),
                ('libelle', models.CharField(blank=True, max_length=500)),
                ('ods_depart', models.DateField(blank=True)),
                ('delais', models.PositiveIntegerField(default=0)),
                ('revisable', models.BooleanField(default=True)),
                ('rabais', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tva', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('code_contrat', models.CharField(blank=True, max_length=20)),
                ('date_signature', models.DateTimeField(auto_now=True, db_column='Date_Signature')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='Date_Modification')),
                ('nt', models.ForeignKey(db_column='numero_marche', on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.nt')),
                ('user_id', models.ForeignKey(db_column='User_ID', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marchés',
                'verbose_name_plural': 'Marchés',
                'unique_together': {('avenant', 'nt')},
            },
        ),
        migrations.CreateModel(
            name='DQE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=600)),
                ('prix_u', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unite', models.CharField(max_length=5)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_q', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.marche')),
            ],
            options={
                'verbose_name': 'DQE',
                'verbose_name_plural': 'DQE',
            },
        ),
    ]
