# Generated by Django 4.1 on 2023-10-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('code_client', models.CharField(db_column='Code_Client', max_length=500, primary_key=True, serialize=False)),
                ('type_client', models.SmallIntegerField(blank=True, db_column='Type_Client', null=True)),
                ('est_client_cosider', models.BooleanField(blank=True, db_column='Est_Client_Cosider', default=False, null=True)),
                ('libelle_client', models.CharField(blank=True, db_column='Libelle_Client', max_length=300, null=True)),
                ('nif', models.CharField(blank=True, db_column='NIF', max_length=50, null=True, unique=True)),
                ('raison_social', models.CharField(blank=True, db_column='Raison_Social', max_length=50, null=True)),
                ('num_registre_commerce', models.CharField(blank=True, db_column='Num_Registre_Commerce', max_length=20, null=True)),
                ('est_bloquer', models.BooleanField(blank=True, db_column='Est_Bloquer', default=False, null=True)),
                ('user_id', models.CharField(blank=True, db_column='User_ID', max_length=15, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='Date_Modification', null=True)),
            ],
            options={
                'verbose_name': 'Clients',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('src', models.ImageField(blank=True, default='default.png', upload_to='Images/Login')),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Images',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
