# Generated by Django 3.2.23 on 2023-11-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dqe',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='historicaldqe',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='dqe',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldqe',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
