# Generated by Django 4.2.7 on 2023-12-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsites',
            name='code_commune_site',
            field=models.CharField(blank=True, db_column='Code_Commune_Site', max_length=50, null=True, verbose_name='Code commune'),
        ),
        migrations.AlterField(
            model_name='historicalsites',
            name='code_division',
            field=models.CharField(blank=True, db_column='Code_Division', max_length=50, null=True, verbose_name='Code division'),
        ),
        migrations.AlterField(
            model_name='historicalsites',
            name='code_filiale',
            field=models.CharField(blank=True, db_column='Code_Filiale', max_length=50, null=True, verbose_name='Code Filiale'),
        ),
        migrations.AlterField(
            model_name='historicalsites',
            name='code_region',
            field=models.CharField(blank=True, db_column='Code_Region', max_length=20, null=True, verbose_name='Code région'),
        ),
        migrations.AlterField(
            model_name='historicalsites',
            name='date_cloture_site',
            field=models.DateField(blank=True, db_column='Date_Cloture_Site', null=True, verbose_name='Cloture'),
        ),
        migrations.AlterField(
            model_name='historicalsites',
            name='date_ouverture_site',
            field=models.DateField(blank=True, db_column='Date_Ouverture_Site', null=True, verbose_name='Ouverture'),
        ),
        migrations.AlterField(
            model_name='historicalsites',
            name='libelle_site',
            field=models.CharField(blank=True, db_column='Libelle_Site', max_length=500, null=True, verbose_name='Libelle du Site'),
        ),
        migrations.AlterField(
            model_name='historicalsites',
            name='responsable_site',
            field=models.CharField(blank=True, db_column='Responsable', max_length=500, null=True, verbose_name='Responsable du Site'),
        ),
        migrations.AlterField(
            model_name='historicalsites',
            name='type_site',
            field=models.PositiveSmallIntegerField(blank=True, db_column='Type_Site', null=True, verbose_name='Type du Site'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='code_commune_site',
            field=models.CharField(blank=True, db_column='Code_Commune_Site', max_length=50, null=True, verbose_name='Code commune'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='code_division',
            field=models.CharField(blank=True, db_column='Code_Division', max_length=50, null=True, verbose_name='Code division'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='code_filiale',
            field=models.CharField(blank=True, db_column='Code_Filiale', max_length=50, null=True, verbose_name='Code Filiale'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='code_region',
            field=models.CharField(blank=True, db_column='Code_Region', max_length=20, null=True, verbose_name='Code région'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='date_cloture_site',
            field=models.DateField(blank=True, db_column='Date_Cloture_Site', null=True, verbose_name='Cloture'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='date_ouverture_site',
            field=models.DateField(blank=True, db_column='Date_Ouverture_Site', null=True, verbose_name='Ouverture'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='libelle_site',
            field=models.CharField(blank=True, db_column='Libelle_Site', max_length=500, null=True, verbose_name='Libelle du Site'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='responsable_site',
            field=models.CharField(blank=True, db_column='Responsable', max_length=500, null=True, verbose_name='Responsable du Site'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='type_site',
            field=models.PositiveSmallIntegerField(blank=True, db_column='Type_Site', null=True, verbose_name='Type du Site'),
        ),
    ]
