# Generated by Django 3.2.23 on 2023-11-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmarche',
            name='date_signature',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='marche',
            name='date_signature',
            field=models.DateField(),
        ),
    ]
