# Generated by Django 4.2.7 on 2023-12-06 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmarche',
            name='code_contrat',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code du contrat'),
        ),
        migrations.AlterField(
            model_name='historicalmarche',
            name='date_signature',
            field=models.DateField(verbose_name='Date de signature'),
        ),
        migrations.AlterField(
            model_name='historicalmarche',
            name='delai_paiement_f',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Delai de paiement'),
        ),
        migrations.AlterField(
            model_name='historicalmarche',
            name='delais',
            field=models.PositiveIntegerField(default=0, verbose_name='Delai'),
        ),
        migrations.AlterField(
            model_name='historicalmarche',
            name='ht',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Prix Hors taxe'),
        ),
        migrations.AlterField(
            model_name='historicalmarche',
            name='libelle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Libelle'),
        ),
        migrations.AlterField(
            model_name='historicalmarche',
            name='nt',
            field=models.ForeignKey(blank=True, db_column='nt', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_sm.nt', verbose_name='Numero Travail'),
        ),
        migrations.AlterField(
            model_name='historicalmarche',
            name='num_avenant',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Avenant N° '),
        ),
        migrations.AlterField(
            model_name='historicalmarche',
            name='ods_depart',
            field=models.DateField(blank=True, verbose_name='ODS de départ'),
        ),
        migrations.AlterField(
            model_name='historicalmarche',
            name='rabais',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de rabais'),
        ),
        migrations.AlterField(
            model_name='historicalmarche',
            name='retenue_de_garantie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Retenue de garantie'),
        ),
        migrations.AlterField(
            model_name='historicalmarche',
            name='revisable',
            field=models.BooleanField(default=True, verbose_name='Est-il révisable ?'),
        ),
        migrations.AlterField(
            model_name='historicalmarche',
            name='ttc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Prix avec taxe'),
        ),
        migrations.AlterField(
            model_name='historicalmarche',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='historicalnt',
            name='code_site',
            field=models.ForeignKey(blank=True, db_column='Code_site', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_sm.sites', verbose_name='Code du Site'),
        ),
        migrations.AlterField(
            model_name='historicalnt',
            name='nt',
            field=models.CharField(db_column='NT', db_index=True, max_length=20, verbose_name='Numero du travail'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='code_contrat',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code du contrat'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='date_signature',
            field=models.DateField(verbose_name='Date de signature'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='delai_paiement_f',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Delai de paiement'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='delais',
            field=models.PositiveIntegerField(default=0, verbose_name='Delai'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='ht',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Prix Hors taxe'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='libelle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Libelle'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='nt',
            field=models.ForeignKey(blank=True, db_column='nt', on_delete=django.db.models.deletion.CASCADE, to='api_sm.nt', verbose_name='Numero Travail'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='num_avenant',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Avenant N° '),
        ),
        migrations.AlterField(
            model_name='marche',
            name='ods_depart',
            field=models.DateField(blank=True, verbose_name='ODS de départ'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='rabais',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de rabais'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='retenue_de_garantie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Retenue de garantie'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='revisable',
            field=models.BooleanField(default=True, verbose_name='Est-il révisable ?'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='ttc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Prix avec taxe'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='nt',
            name='code_site',
            field=models.ForeignKey(db_column='Code_site', on_delete=django.db.models.deletion.CASCADE, to='api_sm.sites', verbose_name='Code du Site'),
        ),
        migrations.AlterField(
            model_name='nt',
            name='nt',
            field=models.CharField(db_column='NT', max_length=20, primary_key=True, serialize=False, verbose_name='Numero du travail'),
        ),
    ]
