# Generated by Django 4.2.7 on 2023-12-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnt',
            name='nt',
            field=models.CharField(db_column='NT', db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='nt',
            name='code_client',
            field=models.ForeignKey(db_column='Code_Client', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_sm.clients'),
        ),
        migrations.AlterField(
            model_name='nt',
            name='nt',
            field=models.CharField(db_column='NT', max_length=20, unique=True),
        ),
    ]
