# Generated by Django 3.2.23 on 2023-11-13 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachements',
            name='estimation_travaux_apres_r',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='attachements',
            name='estimation_travaux_avant_r',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='attachements',
            name='qte_realise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
