# Generated by Django 4.2.7 on 2023-12-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='datenais',
            field=models.DateField(null=True),
        ),
    ]
