# Generated by Django 4.2.7 on 2024-01-02 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='au',
            field=models.DateField(verbose_name='Au'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='du',
            field=models.DateField(verbose_name='Du'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='marche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Marche_Facture', to='api_sm.marche', verbose_name='Marche'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='numero_facture',
            field=models.CharField(max_length=800, primary_key=True, serialize=False, verbose_name='Numero de facture'),
        ),
    ]
