# Generated by Django 4.2.7 on 2023-12-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nt',
            old_name='libelle_nt',
            new_name='libelle',
        ),
        migrations.AlterField(
            model_name='dqe',
            name='code_tache',
            field=models.CharField(db_column='Code_Tache', max_length=30, verbose_name='Code de la tache'),
        ),
        migrations.AlterField(
            model_name='dqe',
            name='est_tache_complementaire',
            field=models.BooleanField(blank=True, db_column='Est_Tache_Complementaire', null=True, verbose_name='Tache complementaire'),
        ),
        migrations.AlterField(
            model_name='dqe',
            name='est_tache_composite',
            field=models.BooleanField(blank=True, db_column='Est_Tache_Composite', null=True, verbose_name='Tache composée'),
        ),
        migrations.AlterField(
            model_name='dqe',
            name='libelle',
            field=models.TextField(db_column='Libelle_Tache', verbose_name='Libelle'),
        ),
        migrations.AlterField(
            model_name='dqe',
            name='marche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='marche_dqe', to='api_sm.marche', verbose_name='Code du marché'),
        ),
    ]
