# Generated by Django 4.2.7 on 2024-01-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banque',
            name='libelle',
            field=models.CharField(editable=False, max_length=600),
        ),
    ]
