# Generated by Django 3.2.23 on 2023-11-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nt',
            options={'verbose_name': 'Numero du travail', 'verbose_name_plural': 'Numero du travail'},
        ),
        migrations.AlterModelOptions(
            name='ordre_de_service',
            options={'verbose_name': 'Ordre de service', 'verbose_name_plural': 'Ordre de service'},
        ),
    ]
