# Generated by Django 4.2.7 on 2024-01-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='heure',
            field=models.TimeField(auto_now=True),
        ),
    ]
