# Generated by Django 4.2.7 on 2024-02-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remboursement',
            name='date',
        ),
    ]
