# Generated by Django 3.2.22 on 2023-11-06 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='user_id',
            field=models.ForeignKey(auto_created=True, db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
