# Generated by Django 4.2.7 on 2023-12-13 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marche',
            name='delais',
            field=models.PositiveIntegerField(default=0, verbose_name='Delai des traveaux'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='nt',
            field=models.ForeignKey(db_column='nt', on_delete=django.db.models.deletion.CASCADE, to='api_sm.nt', verbose_name='Numero Travail'),
        ),
    ]
