# Generated by Django 3.2.23 on 2023-11-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnt',
            name='libelle_nt',
            field=models.CharField(blank=True, db_column='Libelle_NT', max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='nt',
            name='libelle_nt',
            field=models.CharField(blank=True, db_column='Libelle_NT', max_length=900, null=True),
        ),
    ]
