# Generated by Django 3.2.23 on 2023-11-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsites',
            name='b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sites',
            name='b',
            field=models.BooleanField(default=False),
        ),
    ]
