# Generated by Django 4.2.7 on 2023-12-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsituationnt',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Situation du Travail', 'verbose_name_plural': 'historical Situation du Travail'},
        ),
        migrations.AlterModelOptions(
            name='situationnt',
            options={'verbose_name': 'Situation du Travail', 'verbose_name_plural': 'Situation du Travail'},
        ),
        migrations.AlterField(
            model_name='factures',
            name='payer',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalfactures',
            name='payer',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
