# Generated by Django 4.2.7 on 2024-01-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dqe',
            options={'permissions': [('upload_dqe', 'Can upload DQE'), ('download_dqe', 'Can download DQE')], 'verbose_name': 'DQE', 'verbose_name_plural': 'DQE'},
        ),
    ]
