# Generated by Django 4.2.7 on 2024-02-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marche',
            name='ods_depart',
            field=models.DateField(blank=True, verbose_name='ODS de démarrage'),
        ),
        migrations.AlterField(
            model_name='ordre_de_service',
            name='motif',
            field=models.TextField(blank=True, null=True, verbose_name='Motif'),
        ),
    ]
