# Generated by Django 4.2.7 on 2024-01-03 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_alter_factures_montant_precedent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='montant_cumule',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Cumulé'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='montant_mois',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant du Mois'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='montant_precedent',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Precedent'),
        ),
    ]
