# Generated by Django 4.2.7 on 2023-12-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_alter_historicalsituationnt_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factures',
            old_name='payer',
            new_name='paye',
        ),
        migrations.RenameField(
            model_name='historicalfactures',
            old_name='payer',
            new_name='paye',
        ),
    ]
