# Generated by Django 4.2.7 on 2024-03-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_attachements_marche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='montant_cumule',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='montant_precedent',
        ),
        migrations.AlterField(
            model_name='attachements',
            name='marche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.marche'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
