# Generated by Django 4.2.7 on 2023-12-19 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_sm', '0002_clients_datenais'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClients',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.CharField(db_column='Code_Client', db_index=True, max_length=500, verbose_name='Code du Client')),
                ('type_client', models.PositiveSmallIntegerField(blank=True, db_column='Type_Client', null=True, verbose_name='Type de Client')),
                ('est_client_cosider', models.BooleanField(blank=True, db_column='Est_Client_Cosider', verbose_name='Est Client Cosider')),
                ('libelle', models.CharField(blank=True, db_column='Libelle_Client', max_length=300, null=True, verbose_name='Libelle')),
                ('adresse', models.CharField(blank=True, db_column='adresse', max_length=500, null=True, verbose_name='Adresse')),
                ('datenais', models.DateField(null=True)),
                ('nif', models.CharField(blank=True, db_column='NIF', db_index=True, max_length=50, null=True, verbose_name='NIF')),
                ('raison_social', models.CharField(blank=True, db_column='Raison_Social', max_length=50, null=True, verbose_name='Raison Social')),
                ('num_registre_commerce', models.CharField(blank=True, db_column='Num_Registre_Commerce', max_length=20, null=True, verbose_name='Numero du registre de commerce')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Clients',
                'verbose_name_plural': 'historical Clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
