# Generated by Django 3.2.23 on 2023-11-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_dqe_prix_ur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dqe',
            name='prix_ur',
        ),
    ]
