# Generated by Django 4.2.7 on 2024-01-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_alter_factures_num_situation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionImpression',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('src', models.ImageField(blank=True, upload_to='Images/Impression')),
                ('type', models.CharField(choices=[('H', 'Header'), ('F', 'Footer')], max_length=20)),
            ],
            options={
                'verbose_name': "Option d'Impression",
                'verbose_name_plural': "Option d'Impression",
            },
        ),
    ]
