# Generated by Django 3.2.22 on 2023-11-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_remove_marche_marche_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marche',
            unique_together={('avenant', 'nt')},
        ),
    ]
