# Generated by Django 4.2.7 on 2023-12-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_alter_historicalmarche_code_contrat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmarche',
            old_name='retenue_de_garantie',
            new_name='rg',
        ),
        migrations.RenameField(
            model_name='marche',
            old_name='retenue_de_garantie',
            new_name='rg',
        ),
    ]
