# Generated by Django 3.2.23 on 2023-11-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_auto_20231129_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsites',
            name='b',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='b',
        ),
    ]
