# Generated by Django 4.2.7 on 2024-02-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_alter_marche_ods_depart_alter_ordre_de_service_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordre_de_service',
            name='date_interruption',
            field=models.DateField(null=True, verbose_name='Date Interruption'),
        ),
        migrations.AlterField(
            model_name='ordre_de_service',
            name='date_reprise',
            field=models.DateField(null=True, verbose_name='Date Reprise'),
        ),
    ]
