# Generated by Django 4.2.7 on 2024-01-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_cautions_taux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautions',
            name='date_soumission',
            field=models.DateField(),
        ),
    ]
