# Generated by Django 3.2.23 on 2023-11-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_auto_20231115_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marche',
            name='ht',
        ),
        migrations.RemoveField(
            model_name='marche',
            name='ttc',
        ),
    ]
