# Generated by Django 3.2.23 on 2023-11-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_revision_prix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision_prix',
            old_name='prix_u',
            new_name='prix_ur',
        ),
        migrations.AlterUniqueTogether(
            name='revision_prix',
            unique_together={('dqe', 'prix_ur')},
        ),
        migrations.RemoveField(
            model_name='revision_prix',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='revision_prix',
            name='unite',
        ),
    ]
