# Generated by Django 4.2.7 on 2023-12-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_rename_libelle_nt_nt_libelle_alter_dqe_code_tache_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nt',
            old_name='libelle',
            new_name='libelle_nt',
        ),
        migrations.AlterField(
            model_name='situationnt',
            name='libelle',
            field=models.CharField(max_length=100, unique=True, verbose_name='Libelle'),
        ),
    ]
