# Generated by Django 3.2.23 on 2023-11-13 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_auto_20231113_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachements',
            options={'verbose_name': 'Attachements', 'verbose_name_plural': 'Attachements'},
        ),
        migrations.AlterField(
            model_name='attachements',
            name='taux',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
