# Generated by Django 4.0 on 2023-11-09 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_alter_cautions_avance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautions',
            name='banque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.banque'),
        ),
    ]
