# Generated by Django 4.2.7 on 2024-01-17 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_remboursement_date_remboursement_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeavance',
            name='divisable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='avance',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='avance',
            name='taux_avance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
