# Generated by Django 4.2.7 on 2023-12-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_alter_attachements_montant_cumule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachements',
            name='dqe',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
