# Generated by Django 4.2.7 on 2024-01-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_alter_factures_au_alter_factures_du_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detailfacture',
            unique_together=set(),
        ),
    ]
