# Generated by Django 4.2.7 on 2024-01-08 14:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_alter_banque_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaissement',
            name='banque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.banque', verbose_name='Banque'),
        ),
        migrations.AlterField(
            model_name='encaissement',
            name='date_encaissement',
            field=models.DateField(verbose_name="Date d'encaissement"),
        ),
        migrations.AlterField(
            model_name='encaissement',
            name='facture',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.factures', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='encaissement',
            name='mode_paiement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.modepaiement', verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='encaissement',
            name='montant_creance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mode en créance'),
        ),
        migrations.AlterField(
            model_name='encaissement',
            name='montant_encaisse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant encaissé'),
        ),
        migrations.AlterField(
            model_name='encaissement',
            name='numero_piece',
            field=models.CharField(max_length=300, verbose_name='Numero de piéce'),
        ),
    ]
