# Generated by Django 4.2.7 on 2024-02-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0002_alter_encaissement_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaissement',
            name='mode_paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.modepaiement', verbose_name='Mode de paiement'),
        ),
    ]
