# Generated by Django 3.2.22 on 2023-11-06 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_sm', '0003_alter_sites_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='user_id',
            field=models.ForeignKey(db_column='User_ID', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
