# Generated by Django 3.2.22 on 2023-11-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_alter_marche_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marche',
            name='ht',
        ),
    ]
