# Generated by Django 4.2.7 on 2024-01-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_alter_encaissement_banque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionimpression',
            name='type',
            field=models.CharField(choices=[('H', 'Header'), ('F', 'Footer')], max_length=20, unique=True),
        ),
    ]
