# Generated by Django 3.2.23 on 2023-11-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_auto_20231122_1112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='revision_prix',
            unique_together=set(),
        ),
    ]
