# Generated by Django 3.2.23 on 2023-11-13 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_auto_20231113_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachements',
            name='taux',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
