# Generated by Django 4.2.7 on 2023-12-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_rename_retenue_de_garantie_historicalmarche_rg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmarche',
            name='num_avenant',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Avenant Numero '),
        ),
        migrations.AlterField(
            model_name='marche',
            name='num_avenant',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Avenant Numero '),
        ),
    ]
