# Generated by Django 4.2.7 on 2024-01-02 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_alter_detailfacture_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='marche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.marche', verbose_name='Marche'),
        ),
    ]
