# Generated by Django 4.2.7 on 2024-01-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_typeavance_divisable_alter_avance_montant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeavance',
            name='divisable',
        ),
    ]
