# Generated by Django 3.2.23 on 2023-11-15 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_auto_20231115_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factures',
            old_name='montant',
            new_name='montant_initial',
        ),
        migrations.AddField(
            model_name='marche',
            name='retenue_de_garantie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='factures',
            name='date_facture',
            field=models.DateField(auto_now=True),
        ),
    ]
