# Generated by Django 4.2.7 on 2024-01-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_alter_cautions_date_soumission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cautions',
            old_name='banque',
            new_name='agence',
        ),
    ]
