# Generated by Django 4.2.7 on 2023-12-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_historicalclients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='datenais',
        ),
        migrations.RemoveField(
            model_name='historicalclients',
            name='datenais',
        ),
    ]
