# Generated by Django 4.2.7 on 2023-12-16 19:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_attachements_dqe'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturerg',
            name='facture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.factures'),
        ),
        migrations.AddField(
            model_name='facturerg',
            name='montant_rg',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='marche',
            name='avenant_du_marche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.marche', verbose_name='Avenant du marche'),
        ),
    ]
