# Generated by Django 4.2.7 on 2024-02-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_alter_ordre_de_service_date_interruption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordre_de_service',
            name='date_interruption',
            field=models.DateField(blank=True, null=True, verbose_name='Date Interruption'),
        ),
        migrations.AlterField(
            model_name='ordre_de_service',
            name='date_reprise',
            field=models.DateField(blank=True, null=True, verbose_name='Date Reprise'),
        ),
    ]
