# Generated by Django 4.2.7 on 2024-03-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0003_remove_factures_montant_cumule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encaissement',
            name='montant_creance',
        ),
    ]
