# Generated by Django 3.2.22 on 2023-11-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0004_remove_marche_ht'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marche',
            name='ttc',
        ),
    ]
