# Generated by Django 4.2.7 on 2023-12-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0004_remove_clients_datenais_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nt',
            old_name='situation',
            new_name='code_situation',
        ),
    ]
