# Generated by Django 4.2.7 on 2024-01-10 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0004_alter_optionimpression_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaissement',
            name='montant_creance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant en créance'),
        ),
    ]
