# Generated by Django 4.2.7 on 2024-01-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0004_remove_typeavance_divisable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remboursement',
            name='montant_precedent',
        ),
    ]
