# Generated by Django 4.2.7 on 2024-03-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0004_remove_encaissement_montant_creance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaissement',
            name='agence',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
