# Generated by Django 4.2.7 on 2024-02-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0004_alter_ordre_de_service_date_interruption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordre_de_service',
            old_name='date_interruption',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='ordre_de_service',
            name='date_reprise',
        ),
        migrations.AddField(
            model_name='ordre_de_service',
            name='rep_int',
            field=models.CharField(blank=True, choices=[('Interruption', 'Interruption'), ('Reprise', 'Interruption')], max_length=300, null=True),
        ),
    ]
