# Generated by Django 4.2.7 on 2023-12-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0004_facturerg_facture_facturerg_montant_rg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marche',
            name='avenant_du_marche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avenant', to='api_sm.marche', verbose_name='Avenant du marche'),
        ),
    ]
