# Generated by Django 4.2.7 on 2024-02-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0004_factures_montan_ava_remb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factures',
            old_name='montan_ava_remb',
            new_name='montant_ava_remb',
        ),
        migrations.RenameField(
            model_name='factures',
            old_name='montan_avf_remb',
            new_name='montant_avf_remb',
        ),
    ]
