# Generated by Django 4.2.7 on 2024-01-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0004_alter_optionimpression_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='num_situation',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='Numero de situation'),
        ),
    ]
