# Generated by Django 3.2.23 on 2023-11-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0005_auto_20231113_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachements',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='attachements',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='attachements',
            name='deleted_by',
        ),
    ]
