# Generated by Django 4.2.7 on 2023-12-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0005_alter_marche_avenant_du_marche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marche',
            name='avenant_du_marche',
        ),
    ]
