# Generated by Django 4.2.7 on 2024-01-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0005_alter_factures_num_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionimpression',
            name='type',
            field=models.CharField(choices=[('H', 'Header'), ('F', 'Footer'), ('EH', 'Empty Header'), ('EF', 'Empty Footer')], max_length=20, unique=True),
        ),
    ]
