# Generated by Django 4.2.7 on 2024-01-03 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0005_alter_factures_montant_cumule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='montant_cumule',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant cumulé'),
        ),
    ]
