# Generated by Django 4.2.7 on 2024-02-08 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0005_rename_montan_ava_remb_factures_montant_ava_remb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursement',
            name='taux_realise',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taux Réalisé'),
        ),
    ]
