# Generated by Django 4.2.7 on 2024-02-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0005_rename_date_interruption_ordre_de_service_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordre_de_service',
            name='rep_int',
            field=models.CharField(choices=[('Interruption', 'Interruption'), ('Reprise', 'Interruption')], default='Interruption', max_length=300),
        ),
    ]
