# Generated by Django 4.2.7 on 2024-01-17 13:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0005_remove_remboursement_montant_precedent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance',
            name='client',
        ),
        migrations.AlterField(
            model_name='avance',
            name='date',
            field=models.DateField(verbose_name="Date d'avance"),
        ),
        migrations.AlterField(
            model_name='avance',
            name='taux_avance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'avance"),
        ),
        migrations.AlterField(
            model_name='avance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_sm.typeavance', verbose_name="Type d'avance"),
        ),
    ]
