# Generated by Django 4.2.7 on 2024-03-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0005_alter_encaissement_agence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remboursement',
            name='montant_cumule',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='rst_remb',
        ),
    ]
