# Generated by Django 4.2.7 on 2023-12-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0005_rename_situation_nt_code_situation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nt',
            old_name='libelle_nt',
            new_name='libelle',
        ),
    ]
