# Generated by Django 4.2.7 on 2024-03-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0006_remove_remboursement_montant_cumule_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remboursement',
            unique_together=set(),
        ),
    ]
