# Generated by Django 4.2.7 on 2023-12-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0006_rename_libelle_nt_nt_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqe',
            name='est_tache_complementaire',
            field=models.BooleanField(blank=True, db_column='Est_Tache_Complementaire', default=False, verbose_name='Tache complementaire'),
        ),
        migrations.AlterField(
            model_name='dqe',
            name='est_tache_composite',
            field=models.BooleanField(blank=True, db_column='Est_Tache_Composite', default=False, verbose_name='Tache composée'),
        ),
    ]
