# Generated by Django 4.2.7 on 2024-02-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0006_remboursement_taux_realise'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attachements',
            unique_together={('dqe', 'date')},
        ),
    ]
