# Generated by Django 4.2.7 on 2024-02-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0007_alter_attachements_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='situation',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='De la Situation N°'),
        ),
    ]
