# Generated by Django 4.2.7 on 2024-03-31 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0007_alter_remboursement_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remboursement',
            unique_together={('facture', 'avance')},
        ),
    ]
