# Generated by Django 4.2.7 on 2023-12-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0008_alter_attachements_montant_cumule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachements',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
