# Generated by Django 4.2.7 on 2024-02-08 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0008_avance_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='fin',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fin'),
        ),
    ]
