# Generated by Django 4.2.7 on 2023-12-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0009_alter_attachements_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachements',
            name='date',
            field=models.DateField(),
        ),
    ]
