# Generated by Django 4.2.7 on 2024-02-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0009_alter_avance_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeavance',
            name='taux_reduction_facture',
        ),
    ]
