# Generated by Django 4.2.7 on 2024-02-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0010_remove_typeavance_taux_reduction_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='situation',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='De la Situation N°'),
        ),
    ]
