# Generated by Django 4.2.7 on 2024-02-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0011_alter_avance_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautions',
            name='est_recupere',
            field=models.BooleanField(default=True),
        ),
    ]
