# Generated by Django 4.2.7 on 2024-02-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0012_alter_cautions_est_recupere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautions',
            name='est_recupere',
            field=models.BooleanField(default=True, verbose_name='Recuperer'),
        ),
    ]
