# Generated by Django 4.2.7 on 2024-02-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0014_alter_cautions_est_recupere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='num_situation',
        ),
        migrations.AlterField(
            model_name='avance',
            name='situation',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Rembourser à partir de la situation n°'),
        ),
    ]
