# Generated by Django 4.2.7 on 2024-02-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0015_remove_factures_num_situation_alter_avance_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='factures',
            name='num_situation',
            field=models.PositiveIntegerField(blank=True, default=0, unique=True, verbose_name='Numero de situation'),
        ),
    ]
