# Generated by Django 4.2.7 on 2024-02-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0016_factures_num_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='num_situation',
            field=models.IntegerField(blank=True, default=0, unique=True, verbose_name='Numero de situation'),
        ),
    ]
