# Generated by Django 4.2.7 on 2024-02-11 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0018_alter_factures_num_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='debut',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Debut'),
        ),
        migrations.AlterField(
            model_name='avance',
            name='fin',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Fin'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='num_situation',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='Numero de situation'),
        ),
    ]
