# Generated by Django 4.2.7 on 2024-02-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0019_alter_avance_debut_alter_avance_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='num_situation',
            field=models.IntegerField(blank=True, default=0, verbose_name='Numero de situation'),
        ),
    ]
