# Generated by Django 4.2.7 on 2024-02-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0020_alter_factures_num_situation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remboursement',
            name='montant_cumule',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='rst_remb',
        ),
    ]
