# Generated by Django 4.2.7 on 2024-02-11 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0021_remove_remboursement_montant_cumule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursement',
            name='montant_cumule',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Cumule'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='rst_remb',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste à rembourser'),
        ),
    ]
