# Generated by Django 4.2.7 on 2024-02-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0022_remboursement_montant_cumule_remboursement_rst_remb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remboursement',
            name='montant_cumule',
        ),
    ]
