# Generated by Django 4.2.7 on 2024-02-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0024_remboursement_montant_cumule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='num_situation',
            field=models.IntegerField(verbose_name='Numero de situation'),
        ),
    ]
