# Generated by Django 4.2.7 on 2024-02-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0027_alter_remboursement_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='type',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('L', 'Images')], max_length=100),
        ),
    ]
