# Generated by Django 4.2.7 on 2024-02-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0028_images_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(blank=True, default=2024)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'TimeLine',
                'verbose_name_plural': 'TimeLine',
            },
        ),
        migrations.AlterField(
            model_name='images',
            name='type',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('L', 'Login')], max_length=100),
        ),
    ]
