# Generated by Django 4.2.7 on 2024-02-12 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0029_timeline_alter_images_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachements',
            name='taux_realiser',
        ),
        migrations.AlterField(
            model_name='avance',
            name='taux_avance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'avance"),
        ),
        migrations.AlterField(
            model_name='marche',
            name='rg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Retenue de garantie'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='tva',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='taux_realise',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taux Réalisé'),
        ),
        migrations.AlterField(
            model_name='typeavance',
            name='taux_max',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='typecaution',
            name='taux_exact',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=38, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='typecaution',
            name='taux_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=38, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='typecaution',
            name='taux_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=38, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
