# Generated by Django 4.2.7 on 2024-02-12 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0031_factures_taux_realise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remboursement',
            name='taux_realise',
        ),
        migrations.AlterField(
            model_name='factures',
            name='taux_realise',
            field=models.DecimalField(decimal_places=5, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)], verbose_name='Taux Realisé'),
        ),
    ]
