# Generated by Django 4.2.7 on 2024-02-12 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0033_alter_factures_taux_realise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='debut',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Debut'),
        ),
        migrations.AlterField(
            model_name='avance',
            name='fin',
            field=models.DecimalField(decimal_places=3, default=80, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Fin'),
        ),
    ]
