# Generated by Django 4.2.7 on 2024-02-12 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0034_alter_avance_debut_alter_avance_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='remb',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remboursement'),
        ),
    ]
