# Generated by Django 4.2.7 on 2024-02-12 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0035_alter_avance_remb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='remb',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remboursement'),
        ),
    ]
