# Generated by Django 4.2.7 on 2024-02-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0036_alter_avance_remb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='situation',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Rembourser à partir de la situation n°'),
        ),
    ]
