# Generated by Django 4.2.7 on 2024-02-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0037_alter_avance_situation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance',
            name='situation',
        ),
    ]
