# Generated by Django 4.2.7 on 2024-02-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0039_alter_avance_debut_alter_avance_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance',
            name='heure',
        ),
    ]
