# Generated by Django 4.2.7 on 2024-02-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0041_alter_cautions_agence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautions',
            name='agence',
            field=models.CharField(db_column='Code_Agence', max_length=500),
        ),
    ]
