# Generated by Django 4.2.7 on 2024-02-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0043_alter_remboursement_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remboursement',
            unique_together=set(),
        ),
    ]
