# Generated by Django 4.2.7 on 2024-02-13 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0045_alter_remboursement_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remboursement',
            name='montant_cumule',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='montant_mois',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='rst_remb',
        ),
        migrations.AddField(
            model_name='remboursement',
            name='montant_cumule_aa',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Cumule AA'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='montant_cumule_af',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Cumule AF'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='montant_mois_aa',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Mois AA'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='montant_mois_af',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Mois AF'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='rst_remb_aa',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste à rembourser AA'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='rst_remb_af',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste à rembourser AF'),
        ),
    ]
