# Generated by Django 4.2.7 on 2024-02-13 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0046_remove_remboursement_montant_cumule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remboursement',
            name='montant_cumule_aa',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='montant_cumule_af',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='montant_mois_aa',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='montant_mois_af',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='rst_remb_aa',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='rst_remb_af',
        ),
        migrations.AddField(
            model_name='remboursement',
            name='montant_cumule',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Cumule'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='montant_mois',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Mois'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='rst_remb',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste à rembourser'),
        ),
    ]
