# Generated by Django 4.2.7 on 2024-02-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0047_remove_remboursement_montant_cumule_aa_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remboursement',
            unique_together={('facture', 'avance')},
        ),
    ]
