# Generated by Django 4.2.7 on 2024-02-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0048_alter_remboursement_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='factures',
            name='is_remb',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
