# Generated by Django 4.2.7 on 2024-02-18 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0050_alter_cautions_agence_alter_factures_is_remb'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='num_situation',
            field=models.IntegerField(blank=True, null=True, verbose_name='De la situation N°'),
        ),
        migrations.AlterField(
            model_name='avance',
            name='debut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Debut'),
        ),
    ]
