# Generated by Django 4.2.7 on 2024-02-18 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0053_alter_avance_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='debut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Debut'),
        ),
    ]
