# Generated by Django 4.2.7 on 2024-02-19 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0056_alter_avance_debut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance',
            name='num_situation',
        ),
        migrations.AlterField(
            model_name='avance',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='avance',
            name='taux_avance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'avance"),
        ),
    ]
