# Generated by Django 4.2.7 on 2024-02-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sm', '0057_remove_avance_num_situation_alter_avance_montant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance',
            name='debut',
        ),
    ]
